### ISSUE TITLE
Getting rid of all_opensource_files

### ISSUE THREAD

**Issue by Androbin** [tensorflow/tensorflow#15758]
This ticket is for tracking the progress of removing the `all_opensource_files` bazel target.
See the discussion in #15368.

- [x] Turn `check_futures_test` into a sanity check #15671
- [x] De-Bazel `check_load_py_test` sanity check #15677
- [x] De-Bazel `pip_smoke_test` sanity check #15678
- [x] Rewrite `//tensorflow/contrib/makefile:build_all_linux`
- [x] Remove `all_opensource_files` bb582f1b6fad474bc446c78a6683247a8eb6048e

**Comment by Androbin** [comment]
@martinwicke Do the proposed refactorings look good to you?

**Comment by Androbin** [comment]
@martinwicke @gunan @jart Do the proposed refactorings look good to you?

**Comment by Androbin** [comment]
@yifeif Which parts of the `makefile` build depend on `all_opensource_files` ?

**Comment by Androbin** [comment]
@gunan What do we need the wrapper around `makefile` builds for?

**Comment by gunan** [comment]
New build infra requires bazel to execute builds. We need to make changes in the infra config to get rid of all opensource files.

@yifeif will need to take a look at that.

**Comment by Androbin** [comment]
Is the `//tensorflow/contrib/makefile:build_all_linux` target even used anywhere?

`grep -r "build_all_linux"` yields just this:
```
./tensorflow/contrib/makefile/README.md:You should then be able to run the `build_all_linux.sh` script to compile:
./tensorflow/contrib/makefile/README.md:tensorflow/contrib/makefile/build_all_linux.sh
./tensorflow/contrib/makefile/BUILD:    name = "build_all_linux",
./tensorflow/contrib/makefile/BUILD:    srcs = ["build_all_linux.sh"],
./tensorflow/contrib/makefile/build_with_docker.sh:COMMAND="tensorflow/contrib/makefile/build_all_linux.sh"
```

Or is the target used somewhere outside this repo?

**Comment by gunan** [comment]
Yes, the infra config we have is outside the repository.

**Comment by Androbin** [comment]
Is the `bazel-run` directory perfectly isolated or can the repository be located in the script?

**Comment by Androbin** [comment]
Either we get rid of the dependency or we remove the boilerplate with bazelbuild/bazel/issues/4577.

**Comment by yifeif** [comment]
FYI we have removed all our dependencies on `all_opensource_files`.

**Comment by Androbin** [comment]
@yifeif Great, could you take a look at #16491 then?

**Comment by tensorflowbutler** [comment]
Nagging Assignee: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @Androbin: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.
