### ISSUE TITLE
Canned TensorForest Tracking

### ISSUE THREAD

**Issue by yupbank** [tensorflow/tensorflow#21830]
Implementation steps for https://github.com/tensorflow/community/blob/master/rfcs/20180626-tensor-forest.md

- [x] classification only and inference only  the tf/core/kernerl part https://github.com/tensorflow/tensorflow/pull/21803
- [ ] classification only and inference only the tf/estimator python part https://github.com/tensorflow/estimator/pull/9
- [ ] classification only and with training https://github.com/tensorflow/tensorflow/pull/23889
- [ ] end2end classification estimator with tests and docs.
- [ ] regression support

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nataliaponomareva: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nataliaponomareva: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nataliaponomareva: It has been 14 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by tensorflowbutler** [comment]
Nagging Assignee @nataliaponomareva: It has been 44 days with no activity and this issue has an assignee. Please update the label and/or status accordingly.

**Comment by whatbeg** [comment]
ohh, it seems that this feature will not be able to be supported in the near future, right?

**Comment by whatbeg** [comment]
@yupbank yeah, thanks, I am using it. looking forward to your early success : )

**Comment by whatbeg** [comment]
hi, @yupbank, may I ask you a question? I found that setting the same base_random_seed for TensorForest generate different classification performance.
For example,
```
params = tf.contrib.tensor_forest.python.tensor_forest.ForestHParams(
num_classes=10, num_features=64, regression=False,
num_trees=50, max_nodes=1000, base_random_seed=2)

classifier = tf.contrib.tensor_forest.client.random_forest.TensorForestEstimator(params)
classifier.fit(x=x_train, y=y_train)
y_out = classifier.predict(x=x_test)

yyy = [x for x in y_out]

y_hat = np.array([x['classes'] for x in yyy])
print(accuracy_score(y_test, y_pred=y_hat))
# first run:  0.9629629629629629
# second run: 0.968013468013468
# third run:  0.9646464646464646
```

The base random seed is non-zero, it's supposed to produce the same result.
Thus, I wonder where else does the code have randomness?
Does this problem lead to a failure to reproduce the results?

**Comment by yupbank** [comment]
which version are you using? this should have been fixed via https://github.com/tensorflow/tensorflow/commit/470305c95c6b607e87ca476e5a109e5993f3cf6f#diff-e8520a546dc972466f7f1c3923bcff6e

**Comment by whatbeg** [comment]
OK, @yupbank , the version is 1.12.0, and I still can see this bug : )

**Comment by sachinprasadhs** [comment]
Hi, I see most of the items you have listed in tracking have been merged/Closed. Could you please close this request if this issue has served it's purpose.Thanks!
